
```{r}
library(caTools)
```


```{r}
# Importing the dataset
dataset = read.csv('Data.csv')
dataset
```

## 1. Taking care of missing data

```{r}

dataset$Age = ifelse(is.na(dataset$Age),
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)),
                     dataset$Age)
dataset$Salary = ifelse(is.na(dataset$Salary),
                        ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)),
                        dataset$Salary)
dataset
```

## 2. Encoding categorical data

```{r}
dataset$Country = factor(dataset$Country,
                         levels = c('France', 'Spain', 'Germany'),
                         labels = c(1, 2, 3))
dataset$Purchased = factor(dataset$Purchased,
                           levels = c('No', 'Yes'),
                           labels = c(0, 1))
dataset
```

## 3. splitting the dataset into taining and test set  (need caTools library)

```{r}
set.seed(123)
# need to prepare the split method
# only need to input y (unlike python)
# Here give percent of train set in SplitRatio
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
split   # gives array of True/False if True=> It will go to training set
```

```{r}
training_set = subset(dataset, split==TRUE)
test_set = subset(dataset, split==FALSE)
```

```{r}
training_set
```

```{r}
test_set
```


## 4. Feature scaling

```{r}
str(dataset)
```


```{r}
training_set[,2:3] <- scale(training_set[,2:3])
training_set
```

```{r}
test_set[,2:3] <- scale(test_set[,2:3])
test_set
```












